language: node_js
node_js:
  - "lts/*"

jobs:
  include:
    - stage: Test
      if: tag IS blank 
      before_install:
        - sudo apt-get install libsecret-1-dev
        - sudo apt-get install fakeroot
      script:
        - npm run lint
        - npm test
        - npm run coverage
        - npm run make
    # Define the release stage that runs semantic-release
    - stage: Create Release
      if: (NOT type IN (pull_request)) AND (branch = master)
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
    # Define the stages that build the binaries and attach them to the release/tag.
    - stage: Build and Deploy
      if: (NOT type IN (pull_request)) AND tag IS present
      os: linux
      before_install:
        - sudo apt-get install libsecret-1-dev
        - sudo apt-get install fakeroot
      before_deploy: echo "{\"apiKey\":\"$BUNGIE_API_KEY\",\"clientId\":\"$BUNGIE_CLIENT_ID\",\"clientSecret\":\"$BUNGIE_CLIENT_SECRET\"}" > config/bungieApp.json
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run publish
        on:
          all_branches: true # We rely on the stage condition.
    - stage: Build and Deploy
      if: tag IS present
      os: osx
      before_deploy: echo "{\"apiKey\":\"$BUNGIE_API_KEY\",\"clientId\":\"$BUNGIE_CLIENT_ID\",\"clientSecret\":\"$BUNGIE_CLIENT_SECRET\"}" > config/bungieApp.json
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run publish
        on:
          all_branches: true # We rely on the stage condition.
    - stage: Build and Deploy
      if: (NOT type IN (pull_request)) AND tag IS present
      os: windows
      before_deploy: echo "{\"apiKey\":\"$BUNGIE_API_KEY\",\"clientId\":\"$BUNGIE_CLIENT_ID\",\"clientSecret\":\"$BUNGIE_CLIENT_SECRET\"}" > config/bungieApp.json
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run publish
        on:
          all_branches: true # We rely on the stage condition.