language: node_js
node_js:
  - "lts/*"

jobs:
  include:
    - stage: Test
      script:
        - npm run lint
        - npm test
        - npm run coverage
        - npm run build
    # Define the release stage that runs semantic-release
    - stage: Create Release
      if: (NOT type IN (pull_request)) AND (branch = master)
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
    - stage: Build and Deploy
      if: (NOT type IN (pull_request)) AND (branch = master) AND tag IS present
      os: linux
      before_script:
        - npm install -g pkg
      script:
        - npm run build
      before_deploy:
        - pkg -o "start" --targets node10-linux-x64 "./dist/index.js"
        - node tools/generateReleaseHierarchy.js
        - zip -r "$TRAVIS_OS_NAME.zip" ./discord-ghost/*
      deploy:
        provider: releases
        api_key: "$GH_TOKEN"
        skip_cleanup: true
        file: "$TRAVIS_OS_NAME.zip"
    - stage: Build and Deploy
      if: (NOT type IN (pull_request)) AND (branch = master) AND tag IS present
      os: osx
      before_script:
        - npm install -g pkg
      script:
        - npm run build
      before_deploy:
        - npm run build
        - pkg -o "start" --targets node10-macos-x64 "./dist/index.js"
        - node tools/generateReleaseHierarchy.js
        - zip -r "$TRAVIS_OS_NAME.zip" ./discord-ghost/*
      deploy:
        provider: releases
        api_key: "$GH_TOKEN"
        skip_cleanup: true
        file: "$TRAVIS_OS_NAME.zip"
    - stage: Build and Deploy
      if: (NOT type IN (pull_request)) AND (branch = master) AND tag IS present
      os: windows
      before_script:
        - npm install -g pkg
      script:
        - npm run build
      before_deploy:
        - choco install zip
        - pkg -o "start" --targets node10-win-x64 "./dist/index.js"
        - node tools/generateReleaseHierarchy.js
        - zip -r "$TRAVIS_OS_NAME.zip" ./discord-ghost/*
      deploy:
        provider: script
        skip_cleanup: true
        script: node tools/releaseWindows.js "$GH_TOKEN"